version: '3.7'
services:
    app:
        container_name: dockerized-react-app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - '1313:3000'
        environment:
            - NODE_ENV=development
        stdin_open: true

